### ISSUE TITLE
wrong temperature value in the climate entity

### ISSUE THREAD

**Issue by fuglphoenix** [superrob/genvexconnect#13]
the climate entity shows the wrong, current temperature. instead of T3 Rum, it shows T4 Afkast
I have a Nilan Comfort 300 with CTS602 
![image](https://github.com/user-attachments/assets/c6752756-e081-41a5-ac30-89553b11bbbc)
![image](https://github.com/user-attachments/assets/3d7bfba8-f4d1-412b-9352-ec2ec63d9354)

**Comment by JEZHDK** [comment]
Hello,

I also wondered on the temperatures of my CTS400 controlled system, and concluded there must be a bug.

Afkast: 21,8
Fraluft: 21,1
Tilluft: 13,2
Udetemperatur: 9,2

I can for sure say that the supply air is not 13,2 dg. It must be the discharge air that is 13,2 dg, and the supply air is the 21,1 dg air.

The Nilan app does not give a lot of help, as it only shows room temp and outdoor temp, is the values are rounded to no decimal. But we can say for sure that the outdoor temp is correct.

**Comment by superrob** [comment]
That is wierd... i am quite sure that i have previously had those two flipped around and had others with the same issue.
Currently it uses the exact same mappings for those 4 sensors as the other ESP32 solutions use.

Is your integration updated to the latest version?

**Comment by JEZHDK** [comment]
Hello,

Yes im running the latest 1.0.1.

I do not know the entire history, but at some point Nilan removed some of the temperatures from their app, because they were showing odd values, maybe that is what is going on?
I can see this on Trustpilot and the reviews in Google play.

**Comment by superrob** [comment]
That might be the case. I would not be supriced if they aren't consistent on different models.
Especially considering that same users do not experience the issue.

On the controller display, do they display the values at their correct positions?
If so, we might have to try and gather some data from the users of the integration.

Namely their model and if the values are displaying correctly. That might show if it is a quirk with individual models, which can be corrected for.

**Comment by fuglphoenix** [comment]
I'm also on the latest version of the integration.
and both the hmi display and the app shows the correct values

**Comment by superrob** [comment]
> Quote reply

I'm guessing it is CTS602 based.
However what model do you have?

**Comment by fuglphoenix** [comment]
![image](https://github.com/user-attachments/assets/7a634884-7d85-483a-8e44-68331870a822)

**Comment by TomBjerre** [comment]
I have a similar or perhaps unrelated issue. I have two instances: an Optima 270 and a CTS 602 controlled unit (home and summerhouse). The values are mixed up, e.g. the Set Point for the Optima is overwriting the CTS (which is lower when I'm not in the summer house). Also, some of the other values fluctuate - e.g., the "Tilluft" which is quite warm in the summerhouse when the built-in in heat pump is active, then it fluctuates between 21 degrees and the actual 40 degrees. Please let me know if there are some logs I can be helpful with.

**Comment by superrob** [comment]
Huh, the Optima and the CTS should not have any influence on each other at all. They should be working as completely seperate entities. 
Do you have both the Genvex and Nilan device added on the same Home assistant server?

**Comment by TomBjerre** [comment]
Yes, they are on the same HA server, and it is actually two Genvex systems using two different emails. It is a Genvex ECO 275 with the Optima 270 controller and a Genvex Premium Preheat 250 XL wit a CTS 602 controller (the one with a heat pump). Not sure what the problem is - I can just see that the numbers bounce back and forth between something that looks correct and something that is way off. It works fine in the Genvex app where I can switch between the two. Any suggestions on how to troubleshoot this?

Speaking of Nilan, I also have a Nilan VPL 15 with a LAN gateway (it says it is a CTS 400 controller) which I cannot figure out how to connect - any hints on how to add a third instance?

**Comment by superrob** [comment]
Are you sure that your other system is actually CTS 602? The Premium Preheat is on Genvex site written to be Optima 301?
What does the integration state for that system? 

Regarding the Nilan unit, is that one also at the same location? You need local access with the current implementation of Nabto.

**Comment by TomBjerre** [comment]
Here I have attached two screenshots taken with 5 seconds difference- you can see how e.g. “Temperature Tilluft” bounces between 34.49 (which matches the Summehouse temperature when the heatpump is active) and 21.8 (which matches the Home temperature in the other instance).
![IMG_4150](https://github.com/user-attachments/assets/e84cda78-e1eb-4f80-9d6e-321ff2b0d6b7)
![IMG_4149](https://github.com/user-attachments/assets/3bd5fc11-128a-4033-b9ac-d9f2bf2533d7)

**Comment by superrob** [comment]
Could you check what controller the integration reports for the Premium Preheat system? It should be Optima 301, not CTS602.

Regarding multiple instances, i actually have no idea if there could be overlap? It shouldn't be the case and the Genvex Nabto connection should be different for each instance. 
However as i have one system myself, that isn't something i have had the ability to actually test.

**Comment by superrob** [comment]
As a troubleshooting step, please try to remove the other system, and see if the one experiencing problems calms down.

**Comment by TomBjerre** [comment]
Thanks, I’ll try that. Now that you mention that the HA system has to be on the same LAN as the ventilation system, it has to be the Nilan and Genvex system that it has picked up, because they are both on my home LAN (still waiting for a fiber in my summer house so that I can connect the two LANs through my Unify setup). Will troubleshoot more when I get home. Best regards, Tom

**Comment by TomBjerre** [comment]
Ok, removing the Genvex Optima 270 solved the problem with the Nilan CTS 602 (it is a VPL 15 Top M2 with a CTS 602 controller) - now the readings seem stable.

Looking into the log, when both instances were loaded, then there were two log entries every 2 minutes. The first one overwriting the value, e.g.  "Ventilator trin" to the value from the Genvex (2), and then setting it back to the value from the Nilan (1):

Nilan anneks Ventilator trin  ændret til Level 1
21.44.28 - For 25 minutter siden

Nilan anneks Ventilator trin  ændret til Level 2
21.41.30 - For 28 minutter siden

Nilan anneks Ventilator trin  ændret til Level 1
21.41.28 - For 28 minutter siden

Nilan anneks Ventilator trin  ændret til Level 2
21.38.29 - For 31 minutter siden

Nilan anneks Ventilator trin  ændret til Level 1
21.38.27 - For 31 minutter siden

Nilan anneks Ventilator trin  ændret til Level 2
21.35.29 - For 34 minutter siden

Nilan anneks Ventilator trin  ændret til Level 1
21.35.27 - For 34 minutter siden

Nilan anneks Ventilator trin  ændret til Level 2
21.32.29 - For 37 minutter siden

In this period the "Ventilator trin" was constant 1.

There is the same pattern for e.g.  "Temperatur mål" switching to the Genvex value of 23 and then back to the real Nilan value of 20:

Ændret til 20,0
21.44.28 - For 31 minutter siden
Ændret til 23,0
21.41.30 - For 34 minutter siden
Ændret til 20,0
21.41.28 - For 34 minutter siden
Ændret til 23,0
21.38.29 - For 37 minutter siden
Ændret til 20,0
21.38.27 - For 38 minutter siden
Ændret til 23,0
21.35.29 - For 40 minutter siden
Ændret til 20,0
21.35.27 - For 41 minutter siden
Ændret til 23,0
21.32.29 - For 43 minutter siden
Ændret til 20,0

I saw the same pattern for e.g. "Tilluft", whereas properties unique for the Nilan like e.g. "Temperatur Fordamper" does not have this behavior. Hence my conclusion is that the two instances somehow overwrite each other's data "registers".

Please let me know if there is some debugging I can help with.

BR/Tom

**Comment by superrob** [comment]
Wierd, so in your case this has nothing to do with the original issue. 
It is an completely different issue, as aparantly having multiple devices added, makes them crosstalk.
That is quite the annoying problem to debug, especially considering that i do not have two devices myself 😅

**Comment by TomBjerre** [comment]
I can understand that. Please let me know if there is anything I can do to help. I'll be happy to install a special build with extra debug info or if there are any experiments you want me to try.

Right now, I'm on vacation in the US, but once I get home, I have an old Pi that I could try to install a debug system on, and I may somehow be able to give you access to it. (I run a Unify setup, so it should be possible for me to set that up without giving you access to my whole network.)

But thanks for the effort so far - much appreciated.

**Comment by superrob** [comment]
I might have located the issue!
Might have been caused by unfamiliarity with python.
I assumed the classes worked the same as with javascript, so i assumed the class variables would be owned by each instance, however that was a wrong assumption. 
Thus the second instance might have effectively overwritten the variables of the first instance.
I am working on a update that should fix the issue :)!

**Comment by TomBjerre** [comment]
Thanks. The multi-instance problem was solved in 1.2.0. It's much appreciated. I will test with three instances next week. Have a great holiday.

**Comment by superrob** [comment]
Great! Good to hear! That was a nice bug to squash :)

**Comment by fuglphoenix** [comment]
my (the original) issue is still not fixed. 
it is still showing the vent afkast temp as current temp

**Comment by superrob** [comment]
The issue were stale since October, and with nobody else reporting the issue 😅
What were the names of the entities, before you renamed them?
Maybe it is the same case as wth the light variant, where Nilan uses "Exhaust" for the room side intake and Genvex uses "Exhaust" for the outside ventning.

**Comment by superrob** [comment]
I have changed the two arround in the latest release.
Are they correct now?

**Comment by superrob** [comment]
Another change! Some models do not have the T3 sensor and just uses the T10 room sensor. This has been changed in the latest version.

**Comment by superrob** [comment]
Well, it is a lot harder when you rename the sensors 😅
Currently you need to switch the names of "Vent afkast" and "Vent rumudsug" around.

**Comment by superrob** [comment]
That said, i can see that the wrong sensor is being pulled for your model.
The CTS602 line can be a bit confusing, as there are a lot of models some with different quirks.
Yours has for example an seperate sensor for the temperature of the air extracted from the room. Only 4 of the many models has that according to the app. So only those models would have the wrong sensor showing the outlet temperature in the current version.

**Comment by fuglphoenix** [comment]
I can imagine that it would be difficult, since the units is sometimes assembled on site.
that being said, I really appreciate you work, it works really well. good job.
about the T3 the temperature of the air extracted from the rooms, i don't see the temperature anywhere ( i've also checked the entities provided). should it be there? if so,  i can try to re-add the integration.

**Comment by fuglphoenix** [comment]
I think that my problem is either:
my extractTempSensor T3 is not added ([here](https://github.com/superrob/genvexnabto/blob/db859b245fa36af1546ff29dca1659248b98d172/src/genvexnabto/models/cts602.py#L113)). which means that it will display the T4 exhaust air instead. which is currently the case...

or:

here the room temp is set to address=41
`GenvexNabtoDatapointKey.TEMP_ROOM: GenvexNabtoDatapoint(address=41, divider=100),`

but here it looks like that if it has extractTempSensor it sets the address to 34... shouldn't it be 41

        if self.deviceHasQuirk("extractTempSensor", self._slaveDeviceModel):  
            self._datapoints[GenvexNabtoDatapointKey.TEMP_EXTRACT] = GenvexNabtoDatapoint(address=34, divider=100)
            self._defaultDatapointRequest.append(GenvexNabtoDatapointKey.TEMP_EXTRACT)
        else:
            self._datapoints[GenvexNabtoDatapointKey.TEMP_EXTRACT] = GenvexNabtoDatapoint(address=41, divider=100)
            self._defaultDatapointRequest.append(GenvexNabtoDatapointKey.TEMP_EXTRACT)

Since i don't know the adress of my room/T3/extract sensor, i don't know if i read the code correctly.
is it possible to view somekind of debug log? with the sensors adresses displayed? 
it would be nice if i could view the address and the temp. that would allow me to determinde the address of the sensor.
and sorry if this doesn't make any sense :-)

**Comment by superrob** [comment]
The sensor namings are extremely confusing.
In Genvex naming it is quite simply. Extract air is the air from the room, and exhaust air is the air leaving the ventilation unit.
However with Nilan it is oposite?
The "Exhaust air" at 34 is actually the temperature of the air being extracted from the room.

**Comment by fuglphoenix** [comment]
The exhaust air (the air that is sent to the outside) is mapped correct. **but** currently that value is **also** mapped to the extract air (room temperature) .   

i saw this [commit ](https://github.com/superrob/genvexnabto/commit/5b8f8b9109ae84a99674b27c7917fd89b9df213a) and thought that my problem might be somewhere here. since it will look for T3 room temperature, and if it doesn't find it, it will use some other temperature: T10. I don't know if you can extract the sensor names, but I don't have a T10. this is the setup i see in my NILAN app:

- T2: supply, air going to the room
- T3 extract, room temperature
- T4 exhaust, air sent to the outside
- T8, outside  temp

**Comment by superrob** [comment]
I was quite confused as to why that should be the issue. 
This is actually fixed a month ago in the current main branch [9e4a6e8](https://github.com/superrob/genvexnabto/commit/9e4a6e8a0300e7644bf8c716cd7318ea6e506b9f) 
However i havn't released those changes yet, due to some other refactoring being done and then being hit with a nice cocktail of being sick for the last two weeks 😅

**Comment by fuglphoenix** [comment]
Great 😁i'm looking forward to it.
